export const SUCCESS = "SUCCESS";
export const LOADING = "LOADING";
export const FAILING = "FAILING";

// Auth
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_FAILING = "REGISTER_FAILING";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_FAILING = "LOGIN_FAILING";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_LOADING = "LOGOUT_LOADING";
export const LOGOUT_FAILING = "LOGOUT_FAILING";

export const RECOVERY_CHECK_EMAIL_SUCCESS = "RECOVERY_CHECK_EMAIL_SUCCESS";
export const RECOVERY_CHECK_EMAIL_LOADING = "RECOVERY_CHECK_EMAIL_LOADING";
export const RECOVERY_CHECK_EMAIL_FAILING = "RECOVERY_CHECK_EMAIL_FAILING";

export const RECOVERY_CHECK_CODE_SUCCESS = "RECOVERY_CHECK_CODE_SUCCESS";
export const RECOVERY_CHECK_CODE_LOADING = "RECOVERY_CHECK_CODE_LOADING";
export const RECOVERY_CHECK_CODE_FAILING = "RECOVERY_CHECK_CODE_FAILING";

export const RECOVERY_SET_PASSWORD_SUCCESS = "RECOVERY_SET_PASSWORD_SUCCESS";
export const RECOVERY_SET_PASSWORD_LOADING = "RECOVERY_SET_PASSWORD_LOADING";
export const RECOVERY_SET_PASSWORD_FAILING = "RECOVERY_SET_PASSWORD_FAILING";

export const EDIT_NAME_SUCCESS = "EDIT_NAME_SUCCESS";
export const EDIT_NAME_LOADING = "EDIT_NAME_LOADING";
export const EDIT_NAME_FAILING = "EDIT_NAME_FAILING";

export const EDIT_EMAIL_SUCCESS = "EDIT_EMAIL_SUCCESS";
export const EDIT_EMAIL_LOADING = "EDIT_EMAIL_LOADING";
export const EDIT_EMAIL_FAILING = "EDIT_EMAIL_FAILING";

export const EDIT_PHOTO_SUCCESS = "EDIT_PHOTO_SUCCESS";
export const EDIT_PHOTO_LOADING = "EDIT_PHOTO_LOADING";
export const EDIT_PHOTO_FAILING = "EDIT_PHOTO_FAILING";

export const EDIT_PASSWORD_SUCCESS = "EDIT_PASSWORD_SUCCESS";
export const EDIT_PASSWORD_LOADING = "EDIT_PASSWORD_LOADING";
export const EDIT_PASSWORD_FAILING = "EDIT_PASSWORD_FAILING";

// Categories
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_LOADING = "GET_CATEGORIES_LOADING";
export const GET_CATEGORIES_FAILING = "GET_CATEGORIES_FAILING";

export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_LOADING = "GET_CATEGORY_LOADING";
export const GET_CATEGORY_FAILING = "GET_CATEGORY_FAILING";

export const GET_COLORS_SUCCESS = "GET_COLORS_SUCCESS";
export const GET_COLORS_LOADING = "GET_COLORS_LOADING";
export const GET_COLORS_FAILING = "GET_COLORS_FAILING";

export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_LOADING = "CREATE_CATEGORY_LOADING";
export const CREATE_CATEGORY_FAILING = "CREATE_CATEGORY_FAILING";

export const EDIT_CATEGORY_SUCCESS = "EDIT_CATEGORY_SUCCESS";
export const EDIT_CATEGORY_LOADING = "EDIT_CATEGORY_LOADING";
export const EDIT_CATEGORY_FAILING = "EDIT_CATEGORY_FAILING";

export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_LOADING = "DELETE_CATEGORY_LOADING";
export const DELETE_CATEGORY_FAILING = "DELETE_CATEGORY_FAILING";

// Projects
export const GET_PROJECTS_BY_CATEGORY_SUCCESS = "GET_PROJECTS_BY_CATEGORY_SUCCESS";
export const GET_PROJECTS_BY_CATEGORY_LOADING = "GET_PROJECTS_BY_CATEGORY_LOADING";
export const GET_PROJECTS_BY_CATEGORY_FAILING = "GET_PROJECTS_BY_CATEGORY_FAILING";

export const GET_USERS_BY_SUBSTRING_SUCCESS = "GET_USERS_BY_SUBSTRING_SUCCESS";
export const GET_USERS_BY_SUBSTRING_LOADING = "GET_USERS_BY_SUBSTRING_LOADING";
export const GET_USERS_BY_SUBSTRING_FAILING = "GET_USERS_BY_SUBSTRING_FAILING";

export const GET_PROJECT_SUCCESS = "GET_PROJECT_SUCCESS";
export const GET_PROJECT_LOADING = "GET_PROJECT_LOADING";
export const GET_PROJECT_FAILING = "GET_PROJECT_FAILING";

export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_LOADING = "CREATE_PROJECT_LOADING";
export const CREATE_PROJECT_FAILING = "CREATE_PROJECT_FAILING";

export const EDIT_PROJECT_SUCCESS = "EDIT_PROJECT_SUCCESS";
export const EDIT_PROJECT_LOADING = "EDIT_PROJECT_LOADING";
export const EDIT_PROJECT_FAILING = "EDIT_PROJECT_FAILING";

export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const DELETE_PROJECT_LOADING = "DELETE_PROJECT_LOADING";
export const DELETE_PROJECT_FAILING = "DELETE_PROJECT_FAILING";

// Tasks
export const GET_TASKS_BY_PROJECT_SUCCESS = "GET_TASKS_BY_PROJECT_SUCCESS";
export const GET_TASKS_BY_PROJECT_LOADING = "GET_TASKS_BY_PROJECT_LOADING";
export const GET_TASKS_BY_PROJECT_FAILING = "GET_TASKS_BY_PROJECT_FAILING";

export const GET_TASK_SUCCESS = "GET_TASK_SUCCESS";
export const GET_TASK_LOADING = "GET_TASK_LOADING";
export const GET_TASK_FAILING = "GET_TASK_FAILING";

export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const CREATE_TASK_LOADING = "CREATE_TASK_LOADING";
export const CREATE_TASK_FAILING = "CREATE_TASK_FAILING";

export const EDIT_TASK_SUCCESS = "EDIT_TASK_SUCCESS";
export const EDIT_TASK_LOADING = "EDIT_TASK_LOADING";
export const EDIT_TASK_FAILING = "EDIT_TASK_FAILING";

export const COMPLETE_TASK_SUCCESS = "COMPLETE_TASK_SUCCESS";
export const COMPLETE_TASK_LOADING = "COMPLETE_TASK_LOADING";
export const COMPLETE_TASK_FAILING = "COMPLETE_TASK_FAILING";

export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_LOADING = "DELETE_TASK_LOADING";
export const DELETE_TASK_FAILING = "DELETE_TASK_FAILING";

export const EDIT_TASK_FORM_DATA_SUCCESS = "EDIT_TASK_FORM_DATA_SUCCESS";

// Subtasks
export const GET_SUBTASKS_BY_TASK_SUCCESS = "GET_SUBTASKS_BY_TASK_SUCCESS";
export const GET_SUBTASKS_BY_TASK_LOADING = "GET_SUBTASKS_BY_TASK_LOADING";
export const GET_SUBTASKS_BY_TASK_FAILING = "GET_TASKS_BY_PROJECT_FAILING";

export const GET_SUBTASK_SUCCESS = "GET_SUBTASK_SUCCESS";
export const GET_SUBTASK_LOADING = "GET_SUBTASK_LOADING";
export const GET_SUBTASK_FAILING = "GET_SUBTASK_FAILING";

export const CREATE_SUBTASK_SUCCESS = "CREATE_SUBTASK_SUCCESS";
export const CREATE_SUBTASK_LOADING = "CREATE_SUBTASK_LOADING";
export const CREATE_SUBTASK_FAILING = "CREATE_SUBTASK_FAILING";

export const EDIT_SUBTASK_SUCCESS = "EDIT_SUBTASK_SUCCESS";
export const EDIT_SUBTASK_LOADING = "EDIT_SUBTASK_LOADING";
export const EDIT_SUBTASK_FAILING = "EDIT_SUBTASK_FAILING";

export const COMPLETE_SUBTASK_SUCCESS = "COMPLETE_SUBTASK_SUCCESS";
export const COMPLETE_SUBTASK_LOADING = "COMPLETE_SUBTASK_LOADING";
export const COMPLETE_SUBTASK_FAILING = "COMPLETE_SUBTASK_FAILING";

export const DELETE_SUBTASK_SUCCESS = "DELETE_SUBTASK_SUCCESS";
export const DELETE_SUBTASK_LOADING = "DELETE_SUBTASK_LOADING";
export const DELETE_SUBTASK_FAILING = "DELETE_SUBTASK_FAILING";

export const EDIT_SUBTASK_FORM_DATA_SUCCESS = "EDIT_SUBTASK_FORM_DATA_SUCCESS";

// Assigned
export const GET_ASSIGNED_SUCCESS = "GET_ASSIGNED_SUCCESS";
export const GET_ASSIGNED_LOADING = "GET_ASSIGNED_LOADING";
export const GET_ASSIGNED_FAILING = "GET_ASSIGNED_FAILING";

export const GET_FILTERED_ASSIGNED_SUCCESS = "GET_FILTERED_ASSIGNED_SUCCESS";
export const GET_FILTERED_ASSIGNED_LOADING = "GET_FILTERED_ASSIGNED_LOADING";
export const GET_FILTERED_ASSIGNED_FAILING = "GET_FILTERED_ASSIGNED_FAILING";

export const GET_CALENDAR_DATES_SUCCESS = "GET_CALENDAR_DATES_SUCCESS";
export const GET_CALENDAR_DATES_LOADING = "GET_CALENDAR_DATES_LOADING";
export const GET_CALENDAR_DATES_FAILING = "GET_CALENDAR_DATES_FAILING";

export const GET_CALENDAR_TASKS_SUCCESS = "GET_CALENDAR_TASKS_SUCCESS";
export const GET_CALENDAR_TASKS_LOADING = "GET_CALENDAR_TASKS_LOADING";
export const GET_CALENDAR_TASKS_FAILING = "GET_CALENDAR_TASKS_FAILING";

export const GET_FILTERED_CALENDAR_TASKS_SUCCESS = "GET_FILTERED_CALENDAR_TASKS_SUCCESS";
export const GET_FILTERED_CALENDAR_TASKS_LOADING = "GET_FILTERED_CALENDAR_TASKS_LOADING";
export const GET_FILTERED_CALENDAR_TASKS_FAILING = "GET_FILTERED_CALENDAR_TASKS_FAILING";